name: Deploy Worker
on:
  workflow_dispatch:
  push:
  pull_request:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      
      - name: Modify wrangler before deployment
        run: |
          sed -i.bak "s/logpush = true/#logpush = true\n[vars]\ntoken = \"${{ secrets.ACCESS_TOKEN }}\"/g" wrangler.toml && rm wrangler.toml.bak
      
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
